### ISSUE TITLE
В классе GameStore метод containsGame при проверке не находит игру добавленную через метод publishGame

### ISSUE THREAD

**Issue by dmitry089** [dmitry089/teamProject#1]
# Описание
В классе GameStore метод containsGame при проверке возвращает false после добавления игры в методе publishGame.

# Локация
   https://github.com/dmitry089/teamProject/blob/e38e2dfb0b98c775086244edd38af68a62c02852/src/main/java/ru/netology/GameStore.java#L28-L39

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/dmitry089/teamProject/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2. Запустить тест **shouldAddGame**
3. Посмотреть на вывод в консоли
**Ожидаемый результат** : Вывод сообщения true. Добавленная игра находится в каталоге игр.
**Фактический результат** : Вывод сообщения false. Добавленной игры нет в  каталоге игр.

# Скриншот
![Скриншот 17-03-2023 222420](https://user-images.githubusercontent.com/119620433/225987784-3bc6cd94-febd-412b-8459-5ec90aaccf3e.jpg)

# Окружение

- Операционная система : Windows 11 Pro Версия 22H2
- IDE : IntelliJ IDEA 2022.3.1 (Community Edition)
- Java : OpenJDK 11

**Comment by LSimutina** [comment]
Внесла изменение в commit "Bug fixes"
