### ISSUE TITLE
В классе GameStore метод getMostPlayer не отображает игрока со временем игры в 1 час

### ISSUE THREAD

**Issue by dmitry089** [dmitry089/teamProject#2]
# Описание
В классе GameStore метод getMostPlayer возвращает null после добавления игрока с временем в 1 час методом addPlayTime.

# Локация дефекта
https://github.com/dmitry089/teamProject/blob/0c79ee70f2e1fe31c614eb8da8109c9765fb6165/src/main/java/ru/netology/GameStore.java#L55-L69

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/dmitry089/teamProject/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2. Запустить тест shouldAddOneHourPlayTime
3. Посмотреть на вывод в консоли

    **Ожидаемый результат** : Вывод сообщения "game"
    **Фактический результат** : Вывод сообщения null. Игрок с временем в 1 час не отображается.

# Скриншот
![Скриншот 18-03-2023 225046](https://user-images.githubusercontent.com/119620433/226130108-0e5e476c-6018-4f96-8098-67848e21538f.jpg)

# Окружение

- Операционная система : Windows 11 Pro Версия 22H2
- IDE : IntelliJ IDEA 2022.3.1 (Community Edition)
- Java : OpenJDK 11

**Comment by LSimutina** [comment]
Внесла изменение в commit "Bug fixes"
