### ISSUE TITLE
В классе GameStore метод containsGame при  добавлении второй игры не отображает в списке через метод publishGame

### ISSUE THREAD

**Issue by dmitry089** [dmitry089/teamProject#3]
# Описание

В классе GameStore метод containsGame при проверке возвращает false после добавления второй игры в методе publishGame.

# Локация
https://github.com/dmitry089/teamProject/blob/44873e0fa47550e470fe4bf85315bea37256af2c/src/main/java/ru/netology/GameStore.java#L28-L39

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/dmitry089/teamProject/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2. Запустить тест shouldAddTwoGames
3. Посмотреть на вывод в консоли

    Ожидаемый результат : Вывод сообщения true. Добавленная игра находится в каталоге игр.
    Фактический результат : Вывод сообщения false. Добавленной игры нет в каталоге игр.

# Скриншот
![Скриншот 18-03-2023 230448](https://user-images.githubusercontent.com/119620433/226130969-42b86db7-f5f9-438a-b29a-05744d887b3c.jpg)

Окружение

- Операционная система : Windows 11 Pro Версия 22H2
- IDE : IntelliJ IDEA 2022.3.1 (Community Edition)
- Java : OpenJDK 11

**Comment by LSimutina** [comment]
Внесла изменение в commit "Bug fixes"
